name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        eventstore-image-tag: ["21.10.9-buster-slim", "22.10.3-buster-slim", "23.10.0-bookworm-slim", "24.2.0-bookworm-slim"]
#        eventstore-image-tag: ["21.10.11-dev"]   # For Joao's dev builds (on ghcr.io).
    env:
      EVENTSTORE_IMAGE_TAG: ${{ matrix.eventstore-image-tag }}
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: make install-poetry
      - name: Install packages
        run: make install-packages
      - name: Lint
        run: make lint
      - name: Check asyncio test case
        run: |
          ! poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncSetupError
          ! poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncTestError
          ! poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncTeardownError
          ! timeout --preserve-status --kill-after=10s 5m poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncSetupError
          ! timeout --preserve-status --kill-after=10s 5m poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncTestError
          ! timeout --preserve-status --kill-after=10s 5m poetry run python -m unittest test_isolated_asyncio_test_case.TestAsyncTeardownError
      - name: Start EventStoreDB
        run: make start-eventstoredb
      - name: Run tests
        run: make test
      - name: Docker logs - secure cluster
        if: success() || failure()
        run: docker compose logs
      - name: Docker logs - insecure server
        if: success() || failure()
        run: docker logs my-eventstoredb-insecure
      - name: Docker logs - secure server
        if: success() || failure()
        run: docker logs my-eventstoredb-secure
      - name: Report memory
        if: success() || failure()
        run: top -bn1
